### ISSUE TITLE
Can't make cadroid accept my certificate

### ISSUE THREAD

**Issue by DamienCassou** [bitfireAT/cadroid#13]
Hi,

I would like to register the certificate of https://www.schplaf.org (serial 00:87:A1:58:04:AB:49:54:82 and sha1 34:C5:98:9B:CA:7D:64:94:9E:D7:9A:D7:C1:99:04:A3:83:BC:90:3F). When I type "schplaf.org" in CAdroid's `Fetch certificate` dialog box, I get this warning:

    The certificate is not issued for "www.schplaf.org" (host name taken from the URL). Use the correct host name or change the subject. You may also use Alternative Subject Names.

But I didn't type "www.schplaf.org" but "schplaf.org". What is the problem? What is "Alternative Subject Names"?

**Comment by rfc2822** [comment]
Does http://schplaf.org redirect to http://www.schplaf.org?

**Comment by DamienCassou** [comment]
Le 21 février 2015 23:00:55 CET, rfc2822 <notifications@github.com> a écrit :
>Does http://schplaf.org redirect to http://www.schplaf.org?

Yes it does

**Comment by rfc2822** [comment]
So this is the reason. Please use the non-directing URL to fetch the certificate.

**Comment by DamienCassou** [comment]
Thank you

**Comment by markus80** [comment]
Alternative Subject Names could/should be written into a certificate. They are additional alternative names (domains, ip addresses). Btw you should use that feature always, although if you only have one name.
Your current certificate uses already the "attribute" for Alternative Subject Names: "DNS name: *.schplaf.org". So the certificate is valid for all subdomains for the domain, but schplaf.org itself not. You should add also schplaf.org to the list of Alternative Subject Names, if possible.

btw: see https://sslcheck.casecurity.org/de/sslcheck?host=www.schplaf.org#80.67.188.118
