### ISSUE TITLE
app terminates when clicking header line above certificate list

### ISSUE THREAD

**Issue by markus80** [bitfireAT/cadroid#15]
i have created a new secp521r1 self-signed certificate for my local server on ip 192.168.178.20 (see below). after i have entered the server address and pressed download, the app terminates.

is that not supported? i also tried it with a dynamic dns server address (in common name and as additional subjectAltName) and the app does not crash, but only shows an overview of the certificate...

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            ca:62:e9:b5:7c:db:e5:2a
    Signature Algorithm: ecdsa-with-SHA512
        Issuer: C=XX, ST=XXXXXX, L=XXXXX, O=XXXXX, CN=192.168.178.20/emailAddress=markus@XXXXX.net
        Validity
            Not Before: Mar 25 22:58:04 2015 GMT
            Not After : Mar 24 22:58:04 2016 GMT
        Subject: C=XX, ST=XXXXXX, L=XXXXX, O=XXXXX, CN=192.168.178.20/emailAddress=markus@XXXXX.net
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (521 bit)
                pub:
                    04:00:2d:c6:d5:fb:16:4f:c9:71:a3:d7:62:58:6e:
                    15:97:81:41:1b:45:42:31:0b:a3:4b:22:fd:b2:a9:
                    11:cc:59:7c:7a:81:ab:11:f6:69:a2:d0:79:f9:85:
                    69:06:34:c4:7c:38:12:a9:df:09:51:2e:ec:8b:63:
                    ed:83:90:ec:d8:4a:42:01:71:23:1c:69:9c:8d:f2:
                    36:00:0d:74:ca:d9:8a:37:f4:a3:3d:88:ef:3b:e2:
                    74:39:91:0e:97:83:87:c7:47:9a:26:17:0d:bf:64:
                    4d:93:47:d8:8c:e8:26:7c:fb:ef:80:a9:34:2c:51:
                    9a:0a:91:88:d1:22:79:0e:a7:ec:1c:35:75
                ASN1 OID: secp521r1
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Key Usage:
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Subject Alternative Name:
                IP Address:192.168.178.20
    Signature Algorithm: ecdsa-with-SHA512
         30:81:88:02:42:01:a4:a0:68:eb:e1:7b:5e:e3:0b:1e:f5:2e:
         e5:9b:db:50:a1:be:ba:2c:1f:7d:57:dd:d1:d6:d3:fe:ae:8a:
         cc:34:38:cb:8e:1e:39:5f:dc:14:f9:01:12:96:f7:94:e3:c7:
         0f:f9:83:1d:ba:82:70:2b:9f:6c:36:01:27:fe:a1:56:4c:02:
         42:01:bd:bf:bd:4d:05:c6:f8:93:0e:6a:14:da:af:e8:55:ad:
         f2:83:e5:ba:df:2e:8a:d4:f6:93:cd:19:a3:51:4a:1f:d2:83:
         40:f6:12:50:b4:8c:07:d6:06:4d:c2:53:8b:de:54:e1:18:06:
         d3:d0:07:e4:09:a1:4b:29:63:6c:2e:01:cf

**Comment by rfc2822** [comment]
> after i have entered the server address and pressed download, the app terminates.

It terminates == it crashes?

> X509v3 Basic Constraints:
> CA:FALSE

So import is not possible, which should be shown by a message below the certicate details. Can you scroll in this view? Is there any text below the certificate details?

**Comment by markus80** [comment]
a system message appears and says something like app has been closed.
in the other case there was no text below that certificate overview section.

must i link the certificate to a certificate authority?

**Comment by rfc2822** [comment]
> must i link the certificate to a certificate authority?

I don't know what you mean. What is your use case? Is the certificate self-signed or signed by another CA?

However, in any case, CAdroid should not crash.

Can you post your FQDN or send it to play@bitfire.at (to keep it secret)?

**Comment by markus80** [comment]
Bugfix provided for devices with Android versions below 4.4 in SelectFragment.java: https://github.com/bitfireAT/cadroid/pull/17

**Comment by markus80** [comment]
solved with release version 1.0.1
