### ISSUE TITLE
Application can't go further step 3:select

### ISSUE THREAD

**Issue by dominix** [bitfireAT/cadroid#16]
I can enter a FQDN, download a certificate,
the application show me one, or sometimes 2 ou 3 lines of certificate, for selection, but I can't choose any. there is no more step, no selectable item, not clickable, not skippable.
at this point nothing append, nothing to do except leave correctly (abandon). no way to go step 4.

**Comment by rfc2822** [comment]
Please provide further details which allow me to identify this issue.

**Comment by dominix** [comment]
what kind of details ? here is no error. NB : I have installed CACert root certificate (and I use cacert certificate)

**Comment by dominix** [comment]
![screenshot_2015-03-28-18-02-10](https://cloud.githubusercontent.com/assets/1034619/6884059/e5c17c92-d574-11e4-9c22-1dcf4b69938f.png)

**Comment by rfc2822** [comment]
Can't reproduce this here. When trying `www.infonecs.pf`, I get the same result as you, and then the certificates are clickable.

So nothing happens when you tap on the first ("CN=CAcert Class …") or any other line of the list?

**Comment by markus80** [comment]
@dominix: Does this happen with Android version below 4.4?

**Comment by dominix** [comment]
it is version 4.1 on a ASUS TF300T

**Comment by markus80** [comment]
I could reproduce the issue. CAdroid would even crash, if the root certificate was not installed.
My provided bugfix https://github.com/bitfireAT/cadroid/pull/17 should solve your issue.

**Comment by dominix** [comment]
thank you for this, I will test ASAP : which of play.google.com f-droid.org or github will be released first ?

**Comment by markus80** [comment]
haha, first should be on github. afterwards on google play store and then f-droid - that was the order of the last release.

**Comment by markus80** [comment]
@rfc2822: we're looking for the merge/review and its release ;)

**Comment by markus80** [comment]
@dominix: Release v1.0.1 available on github: https://github.com/bitfireAT/cadroid/releases.

**Comment by dominix** [comment]
ok, tested, it work fine

**Comment by markus80** [comment]
thank you for your feedback. that makes me glad. :)

**Comment by dominix** [comment]
you desserve it.
