### ISSUE TITLE
Reusing http connections are buggy with versions before Android 4.1 (API Level 16)

### ISSUE THREAD

**Issue by markus80** [bitfireAT/cadroid#18]
applies only for poor server configuration.

For reproducing:
Fetch certificate for https://www.infonecs.pf, go back and re-fetch it => CAdroid crashs

**Comment by markus80** [comment]
This issue will be solved by the provided commit / pull request.

**Comment by rfc2822** [comment]
I can reproduce the problem and see that `getCertificates()` doesn't provide certificates. Why is that? Is this bug documented somewhere?

**Comment by markus80** [comment]
yes, that is a known bug in Android version below 4.1:
http://stackoverflow.com/questions/3352424/httpurlconnection-openconnection-fails-second-time

**Comment by rfc2822** [comment]
And how is it related to poorly configurated servers?

**Comment by markus80** [comment]
Those servers disabled keep alive connections.
