### ISSUE TITLE
subjectAltName is ignored

### ISSUE THREAD

**Issue by RunningDroid** [bitfireAT/cadroid#21]
When I access my server from the alternate name(192.168.2.42) instead of the common name(storagebot.teh-server.com), cadroid ignores the subjectAltName and says the cert is invalid.

screenshot:
![screenshot_2015-05-04-20-10-08][1]

[1]: https://cloud.githubusercontent.com/assets/486393/7465192/363176d6-f29a-11e4-9731-c0285a4dd9c6.png

**Comment by markus80** [comment]
have you inserted the address https://192.168.2.42 into the input field?

**Comment by RunningDroid** [comment]
No I put 198.168.2.42 in the input field, if I put https://192.168.2.42 in the input field it does something different.

screenshot:
![screenshot_2015-05-05-10-44-29][1]

[1]: https://cloud.githubusercontent.com/assets/486393/7504228/89aca498-f416-11e4-9c46-c7cca2b53081.png

**Comment by markus80** [comment]
What Android version do you use for that issue?

**Comment by RunningDroid** [comment]
I'm running Android 4.1.2.
I don't know where it gets 198.105.244.228 from, the only redirect I have setup on the server is http to https.

**Comment by rfc2822** [comment]
Can you post the certificate (without private keys, of course) here? Did you set 192.168.2.42 as "IP address" or "DNS name" in the certificate? Does it work in browsers? Do you think this is a CAdroid issue or a certificate issue and why? Please provide more information so that we are able to find the reason for your problem.

**Comment by RunningDroid** [comment]
Here's [the certificate][1], I have 192.168.2.42 set as "IP address". The certificate works in Firefox, which is why I think this is a CAdroid issue.

[1]: https://gist.github.com/RunningDroid/ae586a09186461bc0ee2

**Comment by rfc2822** [comment]
Thanks, this has been verified and fixed now (at least here).
