### ISSUE TITLE
Import of self signed certificate failed

### ISSUE THREAD

**Issue by hitam4450** [bitfireAT/cadroid#23]
After adding my host Ip address i selected Weiter an dreceived an error message saying: Die Zertifikatskette beinhaltet kein für die URL-Host Ausgestelltes bZertifikat. benutzen Sie den richtigen Hostname oder ändern sie das entsprechende Zertifikat.

CN= IP-adresse des host, O= IP-Adresse des host.

What is the Zertifikatskette????

What causes this error message?

regards, hiam4450

**Comment by hitam4450** [comment]
Erledigt!

**Comment by markus80** [comment]
for all others: Zertifikatskette = certificate chain

Die Zertifikatskette beinhaltet kein für die URL-Host Ausgestelltes bZertifikat. benutzen Sie den richtigen Hostname oder ändern sie das entsprechende Zertifikat. = The certificate chain does not contain a certificate issued for the host of the URL. Please use the correct hostname or change the corresponding certificate

**Comment by rfc2822** [comment]
https://github.com/bitfireAT/cadroid/blob/master/app/src/main/res/values/strings.xml#L48

When using English locale, the strings should be English?!
