### ISSUE TITLE
Doesn't work with Synology NAS?

### ISSUE THREAD

**Issue by OderDochNicht** [bitfireAT/cadroid#3]
Trying to fetch the self created and signed certificate from my Synology NAS (DSM 5.0-4493 Update 3, IP:port 192.168.233.19:5001) I'm getting the error: "failed to connect to /192.168.233.19 (port 5001): connect failed: ECONNREFUSED (Connection refused).

Phone: Huawei U8860, Cyanogenmod 11-20140621-UNOFFICIAL-u8860, Android 4.4.4, Kernel 3.0.101-rc1-perf-gcf023ba-dirty Desalesouche@NoGiveUp-FR #1 Sat Jun 21 03:53:31 CEST 2014

**Comment by phieber** [comment]
I have the very same error. Maybe a cipher suite or new protocol that's not supported by CAdroid?

**Comment by rfc2822** [comment]
As there are too many different questions and issues in this issue, please open a new one if your problem still persists with CAdroid 0.9.9 (to be released soon).
